language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install .
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pip install flake8; fi
script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then flake8; fi
